stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  before_script:
    - cp ${PROD_ENV} .env_prod
    - cp ${TEST_ENV} .env_test
  script:
    - docker build -t booking_back_image .


#test-job:
#  stage: test
#  script:
#    - echo "Hello World"

deploy-job:
  stage: deploy
  script:
    - docker compose -f docker-compose-ci.yml up -d
    - docker exec booking_back_nginx nginx -s reload